# Generated by Django 4.2.6 on 2023-10-24 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nombre')),
                ('slug', models.SlugField(help_text='Una URL-amigable representación del nombre', unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nombre')),
                ('slug', models.SlugField(help_text='Una URL-amigable representación del nombre', unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('title', models.CharField(max_length=200, verbose_name='titulo')),
                ('slug', models.SlugField(help_text='Una URL-amigable representación del titulo', unique=True, verbose_name='slug')),
                ('content', models.TextField(verbose_name='contenido')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='imagen')),
                ('published', models.BooleanField(default=False, verbose_name='publicado')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('categories', models.ManyToManyField(related_name='get_posts', to='blogs.category', verbose_name='categorias')),
                ('tags', models.ManyToManyField(related_name='get_posts', to='blogs.tag', verbose_name='etiquetas')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
            },
        ),
    ]
